### ISSUE TITLE
Trying to initialize ImGUI throws an exception

### ISSUE THREAD

**Issue by Lioncat2002** [dovker/Monogame.ImGui#3]
When I try to initialize the renderer in the void Initialize methode it gives this error
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.Xna.Framework.TextInputEventArgs' from assembly 'MonoGame.ImGui, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.
  Source=MonoGame.ImGui
  StackTrace:
   at MonoGame.ImGui.Data.InputData.Initialize(Game game)
   at MonoGame.ImGui.ImGUIRenderer.Initialize()
   at imguitest.Game1.Initialize() in D:\monogame\imguitest\Game1.cs:line 24
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at imguitest.Program.Main() in D:\monogame\imguitest\Program.cs:line 11
```
Here is my code:
tho it's pretty much the example code
```cs
public class Game1 : Game
    {
        private GraphicsDeviceManager _graphics;
        private SpriteBatch _spriteBatch;
        public ImGUIRenderer renderer;
        public Game1()
        {
            _graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible = true;
            
        }

        protected override void Initialize()
        {
            // TODO: Add your initialization logic here
            renderer = new ImGUIRenderer(this).Initialize().RebuildFontAtlas();
            base.Initialize();
        }
```

**Comment by Lioncat2002** [comment]
I fixed the issue
The nuget package is outdated thus making it incompatible with the most recent versions of monogame(monogame 3.8)
Directly downloading the source into my project fixed the issue
